# Generated by Django 3.0.7 on 2020-07-07 22:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DateTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InputDT', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
