# Generated by Django 3.0.7 on 2020-07-10 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timezone', '0002_auto_20200709_2323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datetime',
            old_name='userDT',
            new_name='User_Date_Time',
        ),
        migrations.RenameField(
            model_name='datetime',
            old_name='userTZ',
            new_name='User_Time_Zone',
        ),
    ]
