# Generated by Django 3.0.7 on 2020-07-15 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timezone', '0004_auto_20200715_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datetime',
            name='User_Date_Time',
            field=models.CharField(default='0000-00-00 00:00', max_length=25),
        ),
    ]
