# Generated by Django 3.0.7 on 2020-07-16 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timezone', '0005_auto_20200715_0134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datetime',
            name='User_Date_Time',
        ),
    ]
