# Generated by Django 3.0.7 on 2020-07-17 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timezone', '0007_datetime_user_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datetime',
            name='User_Date_Time',
            field=models.CharField(default='0000-00-00 00:00', max_length=16),
        ),
    ]
